name: lendingclub
version: 1.0.0
config-version: 2
profile: default

target-path: "target"
models:
  lendingclub:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
