services:
  pipeline:
    build: .
    ports:
      - "3000:3000"

    volumes:
      - ./pipeline:/app/pipeline
      - ./dbt:/app/dbt
      - ./data:/app/data
      - ./dbt/warehouse.duckdb:/app/dbt/warehouse.duckdb

    command: ["dagster", "dev", "-m", "pipeline", "-h", "0.0.0.0", "-p", "3000", "-d", "/app"]